version: "3.8"
services:
  db:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: root-db
    ports:
      - 27017:27017
    volumes:
      - mongodb_test:/data/db

volumes:
  mongodb_test: