### List users
GET /users HTTP/1.1
Host: localhost:9000
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWFmMmVjNGQ3YTYyZDRlMDRiNmVjOCIsImVtYWlsIjoidXNlcjJAZW1haWwuY29tIiwiaWF0IjoxNjcyMTU2NjI4fQ.tM8kHt47MApO7yn1R0ROYinMpLtk_NY1LK0I1Fpw8Rw

### Register user

POST /users HTTP/1.1
Host: localhost:9000
Content-Type: application/json

{
    "name": "John Doe",
    "email": "user2@email.com",
    "username": "user2",
    "password": "password",
    "id": "2345"
}

### Upload file
POST /users/upload HTTP/1.1
Host: localhost:9000
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="readme"; filename="README.md"

< ../README.md
--WebAppBoundary--

### Login user
POST /login HTTP/1.1
Host: localhost:9000
Content-Type: application/json

{
    "email": "user2@email.com",
    "password": "password"
}