### List users
GET /users HTTP/1.1
Host: localhost:9000
Content-Type: application/json

### Register user

POST /users HTTP/1.1
Host: localhost:9000
Content-Type: application/json

{
    "email": "user1@email.com",
    "username": "user1",
    "id": "2345"
}

### Upload file
POST /users/upload HTTP/1.1
Host: localhost:9000
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="readme"; filename="README.md"

< ../README.md
--WebAppBoundary--