@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWI1ZjhjYTc2NWJmODQ0ZmJmMzM2NSIsImVtYWlsIjoidXNlckBlbWFpbC5jb20iLCJpYXQiOjE2NzIxNzU1NzJ9.uuFymQh7bh_6P-e78bydOfxbskUt5rlLA9e0T_ZSzN0

@id = 63ab5f8ca765bf844fbf3365

### List users
GET /users HTTP/1.1
Host: localhost:9000
Content-Type: application/json
Authorization: {{token}}

### Register user
POST /users HTTP/1.1
Host: localhost:9000
Content-Type: application/json

{
    "name": "John Doe",
    "email": "user@email.com",
    "username": "user",
    "password": "password"
}

### Upload file
POST /users/upload HTTP/1.1
Host: localhost:9000
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="readme"; filename="README.md"

< ../README.md
--WebAppBoundary--

### Login user
POST /login HTTP/1.1
Host: localhost:9000
Content-Type: application/json

{
    "email": "user@email.com",
    "password": "password"
}

### Get user
GET /users/{{id}} HTTP/1.1
Host: localhost:9000
Content-Type: application/json
Authorization: {{token}}

### Delete User
DELETE /users/{{id}} HTTP/1.1
Host: localhost:9000
Content-Type: application/json
Authorization: {{token}}